In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
loan=pd.read_csv('/content/Loan Prediction train (1).csv')
loan.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,128,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141,360.0,1.0,Urban,Y

In [ ]:
loan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    int64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(3), int64(2), object(8)
memory usage: 62.5+ KB

In [ ]:
loan=loan.drop(columns=['Loan_ID'])

In [ ]:
loan.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,128,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141,360.0,1.0,Urban,Y

In [ ]:
loan.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [ ]:
loan.shape

(614, 12)

In [ ]:
loan.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
loan['Gender'].value_counts()

Gender
Male      489
Female    112
Name: count, dtype: int64

In [ ]:
loan['Gender']=loan['Gender'].fillna('Male')

In [ ]:
loan.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
loan['Self_Employed'].value_counts()

Self_Employed
No     500
Yes     82
Name: count, dtype: int64

In [ ]:
loan['Self_Employed']=loan['Self_Employed'].fillna('No')

In [ ]:
loan['Dependents'].value_counts()

Dependents
0     345
1     102
2     101
3+     51
Name: count, dtype: int64

In [ ]:
loan['Dependents']=loan['Dependents'].fillna('0')

In [ ]:
loan['Loan_Amount_Term'].skew()

np.float64(-2.362414124216269)

In [ ]:
loan['Loan_Amount_Term']=loan['Loan_Amount_Term'].fillna(loan['Loan_Amount_Term']).median()

In [ ]:
loan['Credit_History'].skew()

np.float64(-2.0219705924848985)

In [ ]:
loan['Credit_History'] = pd.to_numeric(loan['Credit_History'], errors='coerce')
loan['Credit_History'] = loan['Credit_History'].fillna(loan['Credit_History'].median())

In [ ]:
loan.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,128,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141,360.0,1.0,Urban,Y

In [ ]:
loan.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents            0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History        0
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
loan['Married'].value_counts()

Married
Yes    398
No     213
Name: count, dtype: int64

In [ ]:
loan=loan.dropna()

In [ ]:
loan.info()

<class 'pandas.core.frame.DataFrame'>
Index: 598 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            598 non-null    object
 1   Gender             598 non-null    object
 2   Married            598 non-null    object
 3   Dependents         598 non-null    object
 4   Education          598 non-null    object
 5   Self_Employed      598 non-null    object
 6   ApplicantIncome    598 non-null    int64
 7   CoapplicantIncome  598 non-null    float64
 8   LoanAmount         598 non-null    int64
 9   Loan_Amount_Term   598 non-null    float64
 10  Credit_History     598 non-null    float64
 11  Property_Area      598 non-null    object
 12  Loan_Status        598 non-null    object
dtypes: float64(3), int64(2), object(8)
memory usage: 65.4+ KB

In [ ]:
cat_col=['Gender','Married','Self_Employed', 'Education','Dependents', 'Property_Area', 'Loan_Status']
for i in cat_col:
  loan[i]=loan[i].astype('category')

In [ ]:
loan.info()

<class 'pandas.core.frame.DataFrame'>
Index: 598 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            598 non-null    object
 1   Gender             598 non-null    category
 2   Married            598 non-null    category
 3   Dependents         598 non-null    category
 4   Education          598 non-null    category
 5   Self_Employed      598 non-null    category
 6   ApplicantIncome    598 non-null    int64
 7   CoapplicantIncome  598 non-null    float64
 8   LoanAmount         598 non-null    int64
 9   Loan_Amount_Term   598 non-null    float64
 10  Credit_History     598 non-null    float64
 11  Property_Area      598 non-null    category
 12  Loan_Status        598 non-null    category
dtypes: category(7), float64(3), int64(2), object(1)
memory usage: 37.7+ KB

In [ ]:
loan_dummy.head()

,Loan_ID,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Gender_Male,Married_Yes,Self_Employed_Yes,Education_Not Graduate,Dependents_1,Dependents_2,Dependents_3+,Property_Area_Semiurban,Property_Area_Urban
0,LP001002,5849,0.0,128,360.0,1.0,Y,True,False,False,False,False,False,False,False,True
1,LP001003,4583,1508.0,128,360.0,1.0,N,True,True,False,False,True,False,False,False,False
2,LP001005,3000,0.0,66,360.0,1.0,Y,True,True,True,False,False,False,False,False,True
3,LP001006,2583,2358.0,120,360.0,1.0,Y,True,True,False,True,False,False,False,False,True
4,LP001008,6000,0.0,141,360.0,1.0,Y,True,False,False,False,False,False,False,False,True

In [ ]:
cat_col=['Gender','Married','Self_Employed', 'Education','Dependents', 'Property_Area']
loan_dummy=pd.get_dummies(loan,columns=cat_col,drop_first=True)

In [ ]:
loan_dummy = pd.get_dummies(loan, columns=cat_col, drop_first=True)
display(loan_dummy.head())

,Loan_ID,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Gender_Male,Married_Yes,Self_Employed_Yes,Education_Not Graduate,Dependents_1,Dependents_2,Dependents_3+,Property_Area_Semiurban,Property_Area_Urban
0,LP001002,5849,0.0,128,360.0,1.0,Y,True,False,False,False,False,False,False,False,True
1,LP001003,4583,1508.0,128,360.0,1.0,N,True,True,False,False,True,False,False,False,False
2,LP001005,3000,0.0,66,360.0,1.0,Y,True,True,True,False,False,False,False,False,True
3,LP001006,2583,2358.0,120,360.0,1.0,Y,True,True,False,True,False,False,False,False,True
4,LP001008,6000,0.0,141,360.0,1.0,Y,True,False,False,False,False,False,False,False,True

In [ ]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()

In [ ]:
loan_dummy['Loan_Status']=le.fit_transform(loan['Loan_Status'])
loan_dummy.head()

,Loan_ID,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Gender_Male,Married_Yes,Self_Employed_Yes,Education_Not Graduate,Dependents_1,Dependents_2,Dependents_3+,Property_Area_Semiurban,Property_Area_Urban
0,LP001002,5849,0.0,128,360.0,1.0,1,True,False,False,False,False,False,False,False,True
1,LP001003,4583,1508.0,128,360.0,1.0,0,True,True,False,False,True,False,False,False,False
2,LP001005,3000,0.0,66,360.0,1.0,1,True,True,True,False,False,False,False,False,True
3,LP001006,2583,2358.0,120,360.0,1.0,1,True,True,False,True,False,False,False,False,True
4,LP001008,6000,0.0,141,360.0,1.0,1,True,False,False,False,False,False,False,False,True

train and test

In [ ]:
x=loan_dummy.drop(columns=['Loan_Status'])
y=loan_dummy['Loan_Status']

In [ ]:
x.head()

,Loan_ID,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Gender_Male,Married_Yes,Self_Employed_Yes,Education_Not Graduate,Dependents_1,Dependents_2,Dependents_3+,Property_Area_Semiurban,Property_Area_Urban
0,LP001002,5849,0.0,128,360.0,1.0,True,False,False,False,False,False,False,False,True
1,LP001003,4583,1508.0,128,360.0,1.0,True,True,False,False,True,False,False,False,False
2,LP001005,3000,0.0,66,360.0,1.0,True,True,True,False,False,False,False,False,True
3,LP001006,2583,2358.0,120,360.0,1.0,True,True,False,True,False,False,False,False,True
4,LP001008,6000,0.0,141,360.0,1.0,True,False,False,False,False,False,False,False,True

In [ ]:
y

0      1
1      0
2      1
3      1
4      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 598, dtype: int64